variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

working pipeline:
  stage: build
  script:
    - echo "Hello World"

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker version
    - docker-compose version
  script:
    - docker-compose down
    - docker-compose build


docker-test:
  image: docker:latest
  stage: test
  services:
    - docker:dind
  before_script:
    - docker version
    - docker-compose version
  script:
    - docker-compose down
    - docker-compose -f docker-compose.tester.yml build
    - docker-compose -f docker-compose.tester.yml up tester
